// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/sqlite.go

// Package mock_pkg is a generated GoMock package.
package mock_pkg

import (
	pkg "ThumbnailsYouTube_/pkg"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// CheckBase mocks base method.
func (m *MockDatabase) CheckBase(filename string) (pkg.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBase", filename)
	ret0, _ := ret[0].(pkg.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBase indicates an expected call of CheckBase.
func (mr *MockDatabaseMockRecorder) CheckBase(filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBase", reflect.TypeOf((*MockDatabase)(nil).CheckBase), filename)
}

// SaveToBase mocks base method.
func (m *MockDatabase) SaveToBase(filename string, image []byte) (pkg.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToBase", filename, image)
	ret0, _ := ret[0].(pkg.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveToBase indicates an expected call of SaveToBase.
func (mr *MockDatabaseMockRecorder) SaveToBase(filename, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToBase", reflect.TypeOf((*MockDatabase)(nil).SaveToBase), filename, image)
}
